# -*- coding: utf-8 -*-
"""Python Assignment-2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DeWUPy_A1aFhB4sSrrqO6HsKDkhQZqHo
"""

alt=900
if alt<1000:
 print("Safe to land")
elif alt>1000 or alt<1000:
 print("Bring down to 1000")
elif alt>5000:
 print("Turn around")
else:
 print("it is the required altitude for landing a plane")

alt=4500
if alt<1000:
 print("Safe to land")
elif alt>1000 and alt<5000:
 print("Bring down to 1000")
elif alt>5000:
 print("Turn around")
else:
 print("it is the required altitude for landing a plane")

alt=6500
if alt<1000:
 print("Safe to land")
elif alt>1000 and alt<5000:
 print("Bring down to 1000")
elif alt>5000:
 print("Turn around")
else:
 print("it is the required altitude for landing a plane")

alt=1000
if alt<1000:
 print("Safe to land")
elif alt>1000 and alt<5000:
 print("Bring down to 1000")
elif alt>5000:
 print("Turn around")
else:
 print("it is the required altitude for landing a plane")

